apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-forcicd
  labels:
    app: flask
    environment: development
    usage: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: malickguess/flaskfordevsecops
          ports:
            - containerPort: 5000
