apiVersion: v1
kind: Service
metadata:
  name: flaskservice
  labels:
    app: flask
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
